bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: "@mahesh-panchal"
  description: An ancient metagenomic profiling workflow
  force: false
  is_nfcore: true
  name: ameta
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
