[workspace]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
name = "nf-core-ameta"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test-local = "nextflow run main.nf -resume -ansi-log false -profile test,docker -dump-channels --outdir results --db_cache 'work/database_cache'"
clean-local = "nextflow clean -f $(nextflow log -q); find work -type d -empty -delete"

[dependencies]
nextflow = ">=25.4.3,<26"
nf-core = ">=3.3.1,<4"
nf-test = ">=0.9.2,<0.10"
