[workspace]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
name = "nf-core-aMeta"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test-local = "nextflow run main.nf -resume -ansi-log false -profile test,docker -dump-channels --outdir results --db_cache 'work/database_cache'"
clean-work = "nextflow clean -f last && find work -type d -empty -delete"
clean-all = "git clean -e .pixi -fdx"

[dependencies]
nextflow = ">=25.10.4,<26"
nf-core = ">=3.5.2,<4"
nf-test = ">=0.9.5,<0.10"
